#!/usr/bin/env python3
"""
Build generated content from the single-source-of-truth data files.

Reads:   data/publications.yml, data/cv.yml
Writes:  publications.qmd   (website Publications page — fancy .pub layout)
         cv.qmd             (website CV page [html] + downloadable PDF [typst])

Runs automatically before every Quarto render (see `pre-render` in _quarto.yml),
so editing a YAML file and pushing updates the site page, the CV page, and the
CV PDF in one go.
"""

import pathlib
import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "data"

STATUS_ORDER = ["published", "under_review", "in_prep", "technical_report"]
STATUS_LABEL = {
    "published": "Published",
    "under_review": "Under review",
    "in_prep": "In advanced preparation",
    "technical_report": "Technical reports",
}


def load(name):
    return yaml.safe_load((DATA / name).read_text(encoding="utf-8"))


def esc_stars(s):
    """Escape equal-contribution asterisks so markdown doesn't read them as emphasis."""
    return (s or "").replace("*", r"\*")


def venue_line(p):
    venue, year, status = p.get("venue"), p.get("year"), p.get("status")
    if not venue:
        return None
    if status in ("published", "technical_report"):
        return f"{venue} · {year}" if year else venue
    if status == "under_review":
        return venue
    if status == "in_prep":
        return f"for {venue}"
    return venue


def groups(entries):
    """Yield (status, [entries]) in canonical order, skipping empty groups."""
    for status in STATUS_ORDER:
        items = [e for e in entries if e.get("status") == status]
        if items:
            yield status, items


# ── website Publications page ────────────────────────────────────────────────

def web_title(p):
    t = p["title"]
    if p.get("url"):
        link = f"[{t}]({p['url']})"
    else:
        link = t
    if p.get("preprint"):
        link = link + " *(preprint)*." if p.get("url") else f"{t} *(preprint)*."
    if p.get("note_html"):
        link += p["note_html"]
    return link


def web_entry(p, kind):
    # .pub-venue / .pub-authors are styled `display:block` in custom.scss, i.e.
    # they are bracketed spans, not fenced divs.
    out = ["::: {.pub}", web_title(p)]
    v = venue_line(p)
    if v:
        out.append("[" + v + "]{.pub-venue}")
    if kind == "first":
        co = p.get("coauthors") or ""
        authors = "with " + esc_stars(co) if co else "Sole author"
    else:
        authors = p.get("authors", "")
    out.append("[" + authors + "]{.pub-authors}")
    out.append(":::")
    return "\n".join(out)


def web_column(entries, kind, heading):
    out = ["::: {.pubs-col}", f"## {heading} ({len(entries)})", ""]
    for status, items in groups(entries):
        out.append("::: {.group-label}")
        out.append(STATUS_LABEL[status])
        out.append(":::")
        out.append("")
        for p in items:
            out.append(web_entry(p, kind))
            out.append("")
    if kind == "first" and any("*" in (e.get("coauthors") or "") for e in entries):
        out.append('::: {style="font-size: 0.78rem; color: #a8a8a8; margin-top: 1.5rem;"}')
        out.append(r"\* equal contribution")
        out.append(":::")
        out.append("")
    out.append(":::")
    return "\n".join(out)


def build_publications(first, contrib):
    body = [
        "---",
        'title: ""',
        'pagetitle: "Publications — Erika C. Freeman"',
        "format:",
        "  html:",
        "    toc: false",
        "    page-layout: full",
        "---",
        "",
        "<!-- GENERATED by scripts/build.py from data/publications.yml — do not edit by hand. -->",
        "",
        "::: {.section-label}",
        "Publications",
        ":::",
        "::: {.section-title}",
        "publications",
        ":::",
        "",
        "::: {.pubs-cols}",
        "",
        web_column(first, "first", "First-author publications"),
        "",
        web_column(contrib, "contrib", "Contributing-author publications"),
        "",
        ":::",
        "",
    ]
    (ROOT / "publications.qmd").write_text("\n".join(body), encoding="utf-8")


# ── CV page (html) + PDF (typst) ─────────────────────────────────────────────

def cv_cite(p, kind):
    if kind == "first":
        co = (p.get("coauthors") or "").replace("*", "")
        authors = "Freeman EC, " + co if co else "Freeman EC"
    else:
        authors = p.get("authors", "")
    title = p["title"].rstrip(".")
    venue, year, status = p.get("venue"), p.get("year"), p.get("status")
    if status == "published":
        if venue and year:
            tail = f"*{venue}* ({year})."
        elif venue:
            tail = f"*{venue}*."
        else:
            tail = f"({year})." if year else ""
    elif status == "technical_report":
        if venue and year:
            tail = f"{venue} ({year})."
        elif venue:
            tail = f"{venue}."
        else:
            tail = f"({year})." if year else ""
    elif status == "under_review":
        tail = f"*{venue}*, in review." if venue else "In review."
    else:
        tail = f"*{venue}*, in prep." if venue else "In prep."
    return f"- {authors}. {title}. {tail}"


def build_cv(cv, first, contrib, protocols):
    pr = cv["profile"]
    meta = (
        f"{pr['email']} · ORCID {pr['orcid']} · "
        f"Google Scholar {pr['scholar']} · {pr['website']} · "
        f"{pr['citizenship']} · {pr['languages']}"
    )

    n_pub_first = sum(1 for p in first if p.get("status") == "published")
    n_other_first = len(first) - n_pub_first
    n_contrib_pub = sum(1 for p in contrib if p.get("status") == "published")

    L = [
        "---",
        'title: ""',
        'pagetitle: "CV — Erika C. Freeman"',
        "format:",
        "  html:",
        "    toc: false",
        "    page-layout: full",
        "  typst:",
        "    papersize: a4",
        "    margin: { x: 1.6cm, y: 1.5cm }",
        "    fontsize: 9.5pt",
        "---",
        "",
        "<!-- GENERATED by scripts/build.py from data/cv.yml + data/publications.yml. -->",
        "",
        ":::: {.cv-page}",
        "",
        f"# {pr['name']} {{.cv-name}}",
        "",
        "[" + pr["tagline"] + "]{.cv-tagline}",
        "",
        "[" + meta + "]{.cv-meta}",
        "",
        '::: {.content-visible when-format="html"}',
        "[Download PDF](cv.pdf){.cv-download}",
        ":::",
        "",
        "## Current position",
        "",
        cv["current_position"].strip(),
        "",
        "## Appointments",
        "",
        "| Role | Institution | Dates |",
        "|---|---|---|",
    ]
    for a in cv["appointments"]:
        L.append(f"| {a['role']} | {a['institution']} | {a['dates']} |")
    L += ["", "## Education", "", "| Degree | Institution | Date | Supervisor(s) |", "|---|---|---|---|"]
    for e in cv["education"]:
        L.append(f"| {e['degree']} | {e['institution']} | {e['date']} | {e.get('supervisors','')} |")

    def section(title, items):
        out = ["", f"## {title}", ""]
        out += [f"- {it}" for it in items]
        return out

    L += section("Research funding & analytical awards", cv["funding"])
    L += section("Honours & awards", cv["honours"])

    L += ["", "## Publications", ""]
    L += [
        f"Full record below. First author: **{n_pub_first} published**, "
        f"{n_other_first} in review or in preparation. "
        f"Co-author: **{n_contrib_pub} published**. "
        f"Metrics via ORCID {pr['orcid']} and Google Scholar ({pr['scholar']}).",
        "",
        "**First-author**",
        "",
    ]
    L += [cv_cite(p, "first") for p in first]
    L += ["", "**Contributing-author**", ""]
    L += [cv_cite(p, "contrib") for p in contrib]

    L += cv_protocols_block(protocols)

    L += section("Invited talks (selected)", cv["talks"])
    L += section("Teaching & mentoring", cv["teaching"])
    L += section("Service & esteem", cv["service"])
    L += ["", "## Skills", "", cv["skills"].strip(), "", "::::", ""]

    (ROOT / "cv.qmd").write_text("\n".join(L), encoding="utf-8")


# ── Protocols (protocols.io) ─────────────────────────────────────────────────

PROTO_ORDER = ["published", "in_prep", "planned"]
PROTO_LABEL = {"published": "Published", "in_prep": "In preparation", "planned": "Planned"}


def proto_entry(p):
    title = p["title"]
    head = f"[{title}]({p['doi']})" if p.get("doi") else title
    out = ["::: {.pub}", head, "[" + (p.get("venue") or "protocols.io") + "]{.pub-venue}"]
    if p.get("note"):
        out.append("[" + p["note"] + "]{.pub-authors}")
    out.append(":::")
    return "\n".join(out)


def build_protocols(data):
    items = data.get("protocols", [])
    body = [
        "---",
        'title: ""',
        'pagetitle: "Protocols — Erika C. Freeman"',
        "format:",
        "  html:",
        "    toc: false",
        "    page-layout: full",
        "---",
        "",
        "<!-- GENERATED by scripts/build.py from data/protocols.yml — do not edit by hand. -->",
        "",
        "::: {.section-label}",
        "Protocols",
        ":::",
        "::: {.section-title}",
        "protocols",
        ":::",
        "",
        data.get("intro", "").strip(),
        "",
        "::: {.pubs-cols}",
        "",
        '::: {.pubs-col style="grid-column: 1 / -1;"}',
        "",
    ]
    for status in PROTO_ORDER:
        grp = [p for p in items if p.get("status") == status]
        if not grp:
            continue
        body += ["::: {.group-label}", PROTO_LABEL[status], ":::", ""]
        for p in grp:
            body += [proto_entry(p), ""]
    body += [":::", "", ":::", ""]
    (ROOT / "protocols.qmd").write_text("\n".join(body), encoding="utf-8")


def cv_protocols_block(data):
    pub = [p for p in data.get("protocols", []) if p.get("status") == "published"]
    out = ["", "## Protocols", ""]
    if pub:
        for p in pub:
            doi = f" {p['doi']}" if p.get("doi") else ""
            out.append(f"- {p['title']}. *{p.get('venue', 'protocols.io')}*.{doi}")
        n_other = len(data.get("protocols", [])) - len(pub)
        if n_other:
            out.append(f"- Additional protocols in preparation for protocols.io ({n_other}).")
    else:
        out.append(data.get("cv_statement",
                   "Lab DOM protocols being published openly on protocols.io; DOIs added as released.").strip())
    return out


def main():
    pubs = load("publications.yml")
    cv = load("cv.yml")
    protocols = load("protocols.yml")
    first = pubs.get("first_author", [])
    contrib = pubs.get("contributing", [])
    build_publications(first, contrib)
    build_protocols(protocols)
    build_cv(cv, first, contrib, protocols)
    print(f"[build] publications.qmd: {len(first)} first-author, {len(contrib)} contributing")
    print(f"[build] protocols.qmd: {len(protocols.get('protocols', []))} protocols")
    print("[build] cv.qmd: html + typst")


if __name__ == "__main__":
    main()
